CREATE TABLE hero (
id VARCHAR(255) NOT NULL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
surname VARCHAR(255) NOT NULL
determinationPoints INT NOT NULL,
heroPoints INT NOT NULL,
destinationPoint INT NOT NULL,
luckPoints INT NOT NULL,
race VARCHAR(255) NOT NULL,
clazz VARCHAR(255) NOT NULL,
profession VARCHAR(255) NOT NULL,
professionLevel VARCHAR(255),
status VARCHAR(255),
age INT NOT NULL,
eyeColor VARCHAR(255) NOT NULL,
hairColor VARCHAR(255) NOT NULL,
height INT NOT NULL,
health INT NOT NULL,
currentExp INT NOT NULL,
totalExp INT NOT NULL
);
CREATE TABLE IF NOT EXISTS ATTRIB (id INT PRIMARY KEY AUTOINCREMENT NOT NULL, hero_id INT NOT NULL, attribute VARCHAR(255), attribLevel INT NOT NULL, attribDeveloped INT NOT NULL);
CREATE TABLE IF NOT EXISTS SKILL (id INT PRIMARY KEY AUTOINCREMENT NOT NULL, hero_id INT NOT NULL, attribute VARCHAR(255), label VARCHAR(255), advances INT NOT NULL, description VARCHAR(255), specialisation VARCHAR(255), isSkillNeedSpecification INT NOT NULL, isBasicSkill INT NOT NULL);
CREATE TABLE IF NOT EXISTS TALENT (id INT PRIMARY KEY AUTOINCREMENT NOT NULL, hero_id INT NOT NULL, name VARCHAR(255) NOT NULL, level INT NOT NULL, description VARCHAR(255));
CREATE TABLE IF NOT EXISTS ITEM (id INT PRIMARY KEY AUTOINCREMENT NOT NULL, heroId INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255), quantity INT NOT NULL, weight INT NOT NULL);
CREATE TABLE IF NOT EXISTS ARMORY_STAFF (hero_id INT NOT NULL, armorName VARCHAR(255) NOT NULL, place VARCHAR(255) NOT NULL, weight INT NOT NULL, armorPoints INT NOT NULL, attributes VARCHAR(255) NOT NULL, PRIMARY KEY(hero_id, place));
CREATE TABLE IF NOT EXISTS WEAPON (id INT PRIMARY KEY AUTOINCREMENT NOT NULL, heroId INT NOT NULL, weaponName VARCHAR(255) NOT NULL, weight INT NOT NULL, rangeLength VARCHAR(255) NOT NULL, damage INT NOT NULL, withStrengthBonus INT NOT NULL, attribs VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS POUCH (heroId INT NOT NULL, gold INT NOT NULL, silver INT NOT NULL, pens INT NOT NULL, PRIMARY KEY(heroId));
